[application]
# These IDs are identical in the supplied DEV and PROD configs.
employee_login = f1410
employee_id = f1400
employee_name = f483
employee_position = f484
employee_phone = f485
employee_max_applications = f13401
employee_folder_number = f13600
employee_work_schedule = f15711
application_metrolog_id = f1740
number = f1660
work_date = f11220
address_id = f11430
address_value = f11340
client_id = f1750
client_value = f435
interval = f11190
status = f1680
phone_number = f1700
phone_number_2 = f11460
floor = f11270
entrance = f11280
entrance_code = f11710
barrier = f13420
comments = f1760
metrolog_comments = f17940
payment_type = f11210
cash_sum = f14021
card_sum = f14031
meter_address_id = f11180
meter_device_kind = f10540
meter_type = f10580
meter_modification = f16061
meter_accuracy_class = f16071
meter_serial_number = f10550
meter_registry_number = f16051
meter_year = f16081
meter_last_check = f10560
meter_next_check = f10570
meter_status = f12740
meter_reading = f16131
