[application]
# These IDs are identical in the supplied DEV and PROD configs.
employee_login = f1410
employee_id = f1400
application_metrolog_id = f1740
number = f1660
work_date = f11220
address_id = f11430
address_value = f11340
client_id = f1750
client_value = f435
interval = f11190
status = f1680
phone_number = f1700
floor = f11270
entrance = f11280
entrance_code = f11710
barrier = f13420
comments = f1760
payment_type = f11210
cash_sum = f14021
card_sum = f14031
